# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 00:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('office', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('war_exp', models.DateField()),
                ('date_assigned', models.DateField()),
                ('asignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Employee')),
            ],
            options={
                'verbose_name_plural': 'Faculty/Staff Computers',
            },
        ),
        migrations.CreateModel(
            name='Lab_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=128)),
                ('comp_count', models.IntegerField(default=0)),
                ('building', models.CharField(max_length=128)),
                ('dept', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Labs/Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('developer', models.CharField(max_length=128)),
                ('lic_exp', models.DateField()),
                ('assigned_dept', models.CharField(max_length=128)),
                ('lisence_type', models.CharField(max_length=128)),
                ('date_assigned', models.DateField()),
                ('license_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('war_exp', models.DateField()),
                ('date_assigned', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Lab_Classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
