# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 23:42
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Software',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Assigned Software',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('office', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('war_exp', models.DateField()),
                ('date_assigned', models.DateField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_database.Employee')),
            ],
            options={
                'verbose_name_plural': 'Faculty/Staff Computers',
            },
        ),
        migrations.CreateModel(
            name='Lab_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=128)),
                ('comp_count', models.IntegerField(default=0)),
                ('building', models.CharField(max_length=128)),
                ('dept', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Labs/Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('developer', models.CharField(max_length=128)),
                ('lic_exp', models.DateField()),
                ('assigned_dept', models.CharField(max_length=128)),
                ('license_type', models.CharField(max_length=128)),
                ('license_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField()),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('war_exp', models.DateField()),
                ('date_assigned', models.DateField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_database.Lab_Classroom')),
            ],
            options={
                'verbose_name_plural': 'Student Computers',
            },
        ),
        migrations.AddField(
            model_name='assigned_software',
            name='faculty_computer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Fac'),
        ),
        migrations.AddField(
            model_name='assigned_software',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Software'),
        ),
        migrations.AddField(
            model_name='assigned_software',
            name='student_computer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Student'),
        ),
    ]
