# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_software',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='assigned_software',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
