# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0002_auto_20180712_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_computer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Fac')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Software')),
                ('student_computer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Student')),
            ],
            options={
                'verbose_name_plural': 'Assigned Software',
            },
        ),
        migrations.AlterModelOptions(
            name='assigned_software',
            options={'verbose_name_plural': 'Assigned Software1'},
        ),
    ]
