# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0002_auto_20180613_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='lisence_type',
            new_name='license_type',
        ),
        migrations.RemoveField(
            model_name='software',
            name='date_assigned',
        ),
        migrations.AlterField(
            model_name='fac',
            name='asignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Employee'),
        ),
    ]
