# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0003_auto_20180712_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_software',
            name='faculty_computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Fac'),
        ),
        migrations.AlterField(
            model_name='assign_software',
            name='student_computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_database.Student'),
        ),
    ]
