# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0004_auto_20180712_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_software',
            name='faculty_computer',
        ),
        migrations.RemoveField(
            model_name='assigned_software',
            name='software',
        ),
        migrations.RemoveField(
            model_name='assigned_software',
            name='student_computer',
        ),
        migrations.DeleteModel(
            name='Assigned_Software',
        ),
    ]
