# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0005_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
