# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_database', '0007_lab_classroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_database.Employee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_database.Lab_Classroom'),
        ),
    ]
